apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - "sleep"
    - "3600"
    image: busybox
    name: busybox
    volumeMounts:
    - name: myvol
      mountPath: /mnt/
      readOnly: true

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: myvol
    configMap:
            name: testconfigmap2
