################################################################################

apiVersion:   v1
kind:         Namespace

metadata:
  name:       pp-ns1

---

################################################################################

apiVersion:   v1
kind:         Pod

metadata:
  name:       pp-busybox
  namespace:  pp-ns1
  labels:
    run:      busybox
spec:
  containers: 
  - image:    busybox
    name:     busybox
    command:
              - sleep
              - "36000"

################################################################################
